#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Security_ms
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SECURITY_MSYSTEM")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertATTENDANCE(ATTENDANCE instance);
    partial void UpdateATTENDANCE(ATTENDANCE instance);
    partial void DeleteATTENDANCE(ATTENDANCE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Security_ms.Properties.Settings.Default.SECURITY_MSYSTEMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ATTENDANCE> ATTENDANCEs
		{
			get
			{
				return this.GetTable<ATTENDANCE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ATTENDANCE")]
	public partial class ATTENDANCE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _EMP_NAME;
		
		private string _IN_TIME;
		
		private string _OUT_TIME;
		
		private string _DUTY_HOURS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMP_NAMEChanging(string value);
    partial void OnEMP_NAMEChanged();
    partial void OnIN_TIMEChanging(string value);
    partial void OnIN_TIMEChanged();
    partial void OnOUT_TIMEChanging(string value);
    partial void OnOUT_TIMEChanged();
    partial void OnDUTY_HOURSChanging(string value);
    partial void OnDUTY_HOURSChanged();
    #endregion
		
		public ATTENDANCE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMP_NAME", DbType="VarChar(MAX)")]
		public string EMP_NAME
		{
			get
			{
				return this._EMP_NAME;
			}
			set
			{
				if ((this._EMP_NAME != value))
				{
					this.OnEMP_NAMEChanging(value);
					this.SendPropertyChanging();
					this._EMP_NAME = value;
					this.SendPropertyChanged("EMP_NAME");
					this.OnEMP_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IN_TIME", DbType="VarChar(MAX)")]
		public string IN_TIME
		{
			get
			{
				return this._IN_TIME;
			}
			set
			{
				if ((this._IN_TIME != value))
				{
					this.OnIN_TIMEChanging(value);
					this.SendPropertyChanging();
					this._IN_TIME = value;
					this.SendPropertyChanged("IN_TIME");
					this.OnIN_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OUT_TIME", DbType="VarChar(MAX)")]
		public string OUT_TIME
		{
			get
			{
				return this._OUT_TIME;
			}
			set
			{
				if ((this._OUT_TIME != value))
				{
					this.OnOUT_TIMEChanging(value);
					this.SendPropertyChanging();
					this._OUT_TIME = value;
					this.SendPropertyChanged("OUT_TIME");
					this.OnOUT_TIMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DUTY_HOURS", DbType="VarChar(MAX)")]
		public string DUTY_HOURS
		{
			get
			{
				return this._DUTY_HOURS;
			}
			set
			{
				if ((this._DUTY_HOURS != value))
				{
					this.OnDUTY_HOURSChanging(value);
					this.SendPropertyChanging();
					this._DUTY_HOURS = value;
					this.SendPropertyChanged("DUTY_HOURS");
					this.OnDUTY_HOURSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
